import { C } from '../theme';

export const home = {
  homeHeader: {
    backgroundColor: C.primary,
    color: '#fff',
    padding: '20px 16px 28px 16px',
    borderBottomLeftRadius: '24px',
    borderBottomRightRadius: '24px',
  },
  homeHeaderInner: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '16px',
  },
  homeSubtitle: {
    fontSize: '0.95rem',
    color: C.accentLight,
    marginBottom: '8px',
    fontWeight: '500',
    letterSpacing: '0.3px',
  },
  homeName: {
    fontSize: '1.6rem',
    marginBottom: '6px',
    lineHeight: 1.3,
    fontWeight: '700',
    letterSpacing: '-0.3px',
  },
  homeForza: {
    fontSize: '0.9rem',
    opacity: 0.85,
    fontWeight: '500',
    letterSpacing: '0.2px',
  },
  homeLogo: {
    width: '56px',
    height: '56px',
    borderRadius: '12px',
    backgroundColor: C.card,
    padding: '2px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    flexShrink: 0,
  },
  homeLogoWrapper: {
    flexShrink: 0,
    marginLeft: 'auto',
    cursor: 'pointer',
  },
  homeQuickActions: {
    display: 'flex',
    gap: '12px',
    width: '100%',
    flex: 1,
  },
  homeSearchBtn: {
    flex: 1,
    width: '100%',
    backgroundColor: C.card,
    color: C.primary,
    padding: '12px 16px',
    borderRadius: C.radiusPill,
    fontWeight: 'bold',
    fontSize: '0.95rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  homeBody: { padding: '16px' },
  homeOperatoreBtn: {
    width: '100%',
    backgroundColor: C.danger,
    color: '#fff',
    padding: '16px',
    borderRadius: C.radiusPill,
    fontWeight: 'bold',
    fontSize: '1.1rem',
    marginBottom: '24px',
    boxShadow: '0 4px 12px rgba(192,57,43,0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    animation: 'operatorePulse 2.5s infinite',
  },
  homeGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    marginBottom: '24px',
  },
  homeNavCard: {
    backgroundColor: C.card,
    padding: '18px 12px',
    borderRadius: C.radiusMd,
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    cursor: 'pointer',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
  },
  homeNavCardIcon: {
    width: '52px',
    height: '52px',
    borderRadius: C.radiusMd,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeNavCardLabel: {
    fontWeight: '600',
    color: C.text,
    fontSize: '0.85rem',
    textAlign: 'center',
  },
  homeBannerBox: {
    backgroundColor: C.warningLight,
    padding: '16px',
    borderRadius: '12px',
    border: `1px solid ${C.warning}`,
    marginBottom: '24px',
  },
  homeBannerTitle: { color: C.warning, marginBottom: '4px', fontWeight: 'bold' },
  homeBannerText: { fontSize: '0.85rem', color: C.text },
  homeAdminBtn: {
    width: '100%',
    backgroundColor: C.text,
    color: '#fff',
    padding: '16px',
    borderRadius: C.radiusPill,
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
  homeLegalCard: {
    marginTop: '24px',
    padding: '16px',
    borderTop: `1px solid ${C.border}`,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  homeLegalRow: { display: 'flex', gap: '16px' },
  homeLegalLink: {
    fontSize: '0.8rem',
    color: C.accent,
    textDecoration: 'underline',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    fontFamily: 'inherit',
  },
  homeLegalVersion: { fontSize: '0.75rem', color: C.textLight },
};
