export const operatore = {
  operatoreContainer: {
    flex: 1,
    backgroundColor: '#121212',
    color: '#e0e0e0',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    overflowY: 'auto',
  },
  operatoreHeader: {
    backgroundColor: '#c0392b',
    padding: '16px',
    color: '#fff',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  operatoreHeaderTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  operatoreHeaderTitle: { fontWeight: 'bold', fontSize: '1.2rem' },
  operatoreExitBtn: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    color: '#fff',
    fontSize: '0.8rem',
    padding: '6px 12px',
    borderRadius: '4px',
    fontWeight: 'bold',
  },
  operatoreHeaderMeta: { display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' },
  operatoreBody: { padding: '16px', flex: 1 },
  operatoreFavLabel: { color: '#f39c12', fontSize: '0.85rem', marginTop: '16px', marginBottom: '12px', fontWeight: 'bold' },
  operatoreItemCard: { backgroundColor: '#1e1e1e', borderRadius: '8px', overflow: 'hidden', border: '1px solid #333' },
  operatoreItemHeader: { padding: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer' },
  operatoreItemRef: { color: '#f39c12', fontWeight: 'bold', fontSize: '0.8rem', marginRight: '8px' },
  operatoreItemTitle: { fontWeight: '600', fontSize: '0.95rem' },
  operatoreDetailPanel: { padding: '12px', borderTop: '1px solid #333', backgroundColor: '#252525' },
  operatoreGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '4px', marginBottom: '12px', textAlign: 'center' },
  operatoreCell: { backgroundColor: '#333', padding: '6px', borderRadius: '4px' },
  operatoreCellWide: { backgroundColor: '#333', padding: '6px', borderRadius: '4px', gridColumn: 'span 2' },
  operatoreCellLabel: { fontSize: '0.65rem', color: '#aaa' },
  operatoreCellValue: { fontSize: '0.9rem', fontWeight: 'bold', color: '#e74c3c' },
  operatoreCellValueGreen: { fontSize: '0.9rem', fontWeight: 'bold', color: '#2ecc71' },
  operatoreDescBlock: { marginBottom: '12px', backgroundColor: 'rgba(255,255,255,0.05)', padding: '8px', borderRadius: '4px' },
  operatoreDescLabel: { fontSize: '0.75rem', color: '#aaa', fontWeight: 'bold', display: 'block', marginBottom: '4px' },
  operatoreDescText: { fontSize: '0.85rem', lineHeight: 1.4 },
  operatoreTagsRow: { display: 'flex', gap: '8px', marginBottom: '12px' },
  operatorePointsBadge: { backgroundColor: '#c0392b', color: '#fff', padding: '4px 8px', borderRadius: '4px', fontSize: '0.8rem', fontWeight: 'bold' },
  operatoreAccessoriaTag: { flex: 1, backgroundColor: '#333', padding: '4px 8px', borderRadius: '4px', fontSize: '0.8rem', color: '#ddd' },
  operatoreNoteOpBlock: { backgroundColor: 'rgba(192, 57, 43, 0.2)', padding: '8px', borderRadius: '4px', borderLeft: '3px solid #e74c3c', marginBottom: '8px' },
  operatoreNoteOpLabel: { fontSize: '0.75rem', color: '#e74c3c', fontWeight: 'bold', display: 'block', marginBottom: '2px' },
  operatoreMemoBlock: { backgroundColor: 'rgba(243, 156, 18, 0.1)', padding: '8px', borderRadius: '4px', borderLeft: '3px solid #f39c12' },
  operatoreMemoLabel: { fontSize: '0.75rem', color: '#f39c12', fontWeight: 'bold', display: 'block', marginBottom: '2px' },
  operatoreTextSm: { fontSize: '0.85rem' },
};
