import { C } from '../theme';

export const profilo = {
  profileHeaderBg: {
    backgroundColor: C.primary,
    padding: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  profileAvatar: {
    width: '60px',
    height: '60px',
    backgroundColor: C.card,
    borderRadius: '30px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '2rem',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    position: 'relative',
  },
  profileHeaderName: { color: '#fff', margin: 0, fontSize: '1.2rem' },
  profileHeaderGrado: { color: '#fff', margin: 0, fontSize: '0.85rem', opacity: 0.9 },
  profileSysBox: {
    backgroundColor: C.card,
    padding: '16px',
    borderRadius: '12px',
    border: `1px solid ${C.border}`,
    marginBottom: '16px',
    flexShrink: 0,
  },
  profileSysTitle: {
    color: C.text,
    marginBottom: '12px',
    fontSize: '0.95rem',
    borderBottom: `1px solid ${C.border}`,
    paddingBottom: '8px',
  },
  profileSupportBox: {
    backgroundColor: C.card,
    padding: '16px',
    borderRadius: '12px',
    textAlign: 'center',
    border: `1px solid ${C.border}`,
    flexShrink: 0,
  },
  profileDonateBtn: {
    display: 'inline-block',
    padding: '10px 20px',
    backgroundColor: '#0070ba',
    color: '#fff',
    borderRadius: '24px',
    textDecoration: 'none',
    fontWeight: 'bold',
    fontSize: '0.9rem',
  },
  profileExitBtn: {
    padding: '6px 12px',
    backgroundColor: C.dangerLight,
    color: C.danger,
    borderRadius: '8px',
    fontWeight: 'bold',
    fontSize: '0.85rem',
  },
};
