export const C = {
  primary:              "var(--color-primary)",
  accent:               "var(--color-accent)",
  accentLight:          "var(--color-accent-light)",
  danger:               "var(--color-danger)",
  dangerLight:          "var(--color-danger-light)",
  success:              "var(--color-success)",
  successLight:         "var(--color-success-light)",
  warning:              "var(--color-warning)",
  warningLight:         "var(--color-warning-light)",
  surface:              "var(--bg-surface)",
  surfaceContainer:     "var(--bg-surface-container)",
  surfaceContainerHigh: "var(--bg-surface-container-high)",
  border:               "var(--color-border)",
  text:                 "var(--color-text)",
  textLight:            "var(--color-text-light)",
  white:                "var(--color-white)",
  background:           "var(--bg-global)",
  card:                 "var(--bg-card)",
  radiusSm:   "var(--radius-sm)",
  radiusMd:   "var(--radius-md)",
  radiusLg:   "var(--radius-lg)",
  radiusXl:   "var(--radius-xl)",
  radiusPill: "var(--radius-pill)",

  // Colori icone pagine — palette coerente
  iconProntuario: { bg: '#dbeafe', color: '#1e40af' },
  iconNormativa:  { bg: '#dcfce7', color: '#15803d' },
  iconCalcola:    { bg: '#fef3c7', color: '#92400e' },
  iconPreferiti:  { bg: '#fee2e2', color: '#991b1b' },
  iconGuide:      { bg: '#f3e8ff', color: '#6b21a8' },
  iconNews:       { bg: '#e0f2fe', color: '#075985' },
  iconLinks:      { bg: '#ccfbf1', color: '#0f766e' },
  iconProfilo:    { bg: '#f1f5f9', color: '#475569' },
  iconRicerca:    { bg: '#fdf4ff', color: '#86198f' },
  iconOperatore:  { bg: '#fee2e2', color: '#991b1b' },
};
