export const C = {
  primary:      "var(--color-primary)",
  accent:       "var(--color-accent)",
  accentLight:  "var(--color-accent-light)",
  danger:       "var(--color-danger)",
  dangerLight:  "var(--color-danger-light)",
  success:      "var(--color-success)",
  successLight: "var(--color-success-light)",
  warning:      "var(--color-warning)",
  warningLight: "var(--color-warning-light)",
  surface:      "var(--bg-surface)",
  border:       "var(--color-border)",
  text:         "var(--color-text)",
  textLight:    "var(--color-text-light)",
  white:        "var(--color-white)",
  background:   "var(--bg-global)",
  card:         "var(--bg-card)",
};
