-- =====================================================
-- MIGRATION: Creazione tabella search_synonyms
-- Data: 2026-07-02
-- Motivo: unificazione motore di ricerca (v1.9.8) — mappa
--   frasi colloquiali/gergali usate sul campo verso la
--   violazione del prontuario corrispondente, per far
--   emergere il risultato giusto come "risultato suggerito"
--   anche quando il testo dell'agente non coincide con il
--   linguaggio giuridico del titolo/descrizione.
-- =====================================================

CREATE TABLE IF NOT EXISTS public.search_synonyms (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  termine       text NOT NULL,                 -- es. "senza assicurazione"
  target_type   text NOT NULL DEFAULT 'prontuario',  -- 'prontuario' | 'normativa' (futuro)
  target_ref    text NOT NULL,                 -- prontuario.codice_caso (NON codice_violazione: è vuoto nel 52% delle righe)
  peso          integer NOT NULL DEFAULT 10,   -- priorità: 10 = curato a mano, 5 = generato automaticamente
  attivo        boolean NOT NULL DEFAULT true,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now(),
  CONSTRAINT search_synonyms_target_type_check CHECK (target_type IN ('prontuario', 'normativa'))
);

CREATE INDEX IF NOT EXISTS idx_search_synonyms_termine
  ON public.search_synonyms (termine);

CREATE INDEX IF NOT EXISTS idx_search_synonyms_target
  ON public.search_synonyms (target_type, target_ref);

-- ─── Trigger: aggiorna updated_at ───────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.search_synonyms_before_update()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_search_synonyms_before_update ON public.search_synonyms;
CREATE TRIGGER trg_search_synonyms_before_update
  BEFORE UPDATE ON public.search_synonyms
  FOR EACH ROW EXECUTE FUNCTION public.search_synonyms_before_update();

-- ─── ROW LEVEL SECURITY (RLS) ────────────────────────────────────────────────
-- Stesso pattern già usato per la tabella prontuario.
ALTER TABLE public.search_synonyms ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "search_synonyms_select_authenticated" ON public.search_synonyms;
CREATE POLICY "search_synonyms_select_authenticated"
  ON public.search_synonyms FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "search_synonyms_select_anon" ON public.search_synonyms;
CREATE POLICY "search_synonyms_select_anon"
  ON public.search_synonyms FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "search_synonyms_insert_admin" ON public.search_synonyms;
CREATE POLICY "search_synonyms_insert_admin"
  ON public.search_synonyms FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND ruolo = 'admin')
  );

DROP POLICY IF EXISTS "search_synonyms_update_admin" ON public.search_synonyms;
CREATE POLICY "search_synonyms_update_admin"
  ON public.search_synonyms FOR UPDATE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND ruolo = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND ruolo = 'admin')
  );

DROP POLICY IF EXISTS "search_synonyms_delete_admin" ON public.search_synonyms;
CREATE POLICY "search_synonyms_delete_admin"
  ON public.search_synonyms FOR DELETE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND ruolo = 'admin')
  );

COMMENT ON TABLE public.search_synonyms IS
  'Sinonimi/frasi colloquiali per la ricerca unificata (v1.9.8). target_ref = prontuario.codice_caso.';

-- ─── SEED: sinonimi generati per i casi più comuni (54 curati a mano + ~120 generati da regole) ───
-- Copertura: 172 violazioni su 989 (le più frequenti nei controlli su strada).
-- Le restanti si possono aggiungere nel tempo dalla pagina Admin > Sinonimi, senza deploy.
INSERT INTO public.search_synonyms (termine, target_type, target_ref, peso, attivo) VALUES
('non da precedenza', 'prontuario', '145-7', 10, true),
  ('salta lo stop', 'prontuario', '145-7', 10, true),
  ('non si ferma allo stop', 'prontuario', '145-7', 10, true),
  ('taglia la strada', 'prontuario', '145-7', 10, true),
  ('non rispetta la precedenza', 'prontuario', '145-7', 10, true),
  ('non tiene la destra', 'prontuario', '143-5', 10, true),
  ('guida al centro della strada', 'prontuario', '143-5', 10, true),
  ('non tiene la corsia giusta', 'prontuario', '143-5', 10, true),
  ('senza autorizzazione', 'prontuario', '010-47', 5, true),
  ('manca autorizzazione', 'prontuario', '010-47', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-47', 5, true),
  ('eccesso di velocità 10-40 km/h', 'prontuario', '142-4bis', 10, true),
  ('supera limite tra 10 e 40 km orari', 'prontuario', '142-4bis', 10, true),
  ('senza avere compiuto 14 anni', 'prontuario', '115-3', 5, true),
  ('senza assicurazione recidiva', 'prontuario', '193-2', 10, true),
  ('senza assicurazione due volte', 'prontuario', '193-2', 10, true),
  ('recidiva assicurazione', 'prontuario', '193-2', 10, true),
  ('senza assicurazione da più di due anni', 'prontuario', '193-2', 10, true),
  ('senza osservarne le norme', 'prontuario', '010-49', 5, true),
  ('manca osservarne le norme', 'prontuario', '010-49', 5, true),
  ('mancanza osservarne le norme', 'prontuario', '010-49', 5, true),
  ('senza autorizzazione', 'prontuario', '123-1', 5, true),
  ('manca autorizzazione', 'prontuario', '123-1', 5, true),
  ('mancanza autorizzazione', 'prontuario', '123-1', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-62', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-62', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-62', 5, true),
  ('senza avere con sé l''autorizzazione', 'prontuario', '114-3', 5, true),
  ('senza patente', 'prontuario', '118-2', 5, true),
  ('manca patente', 'prontuario', '118-2', 5, true),
  ('mancanza patente', 'prontuario', '118-2', 5, true),
  ('senza concessione', 'prontuario', '025-1', 5, true),
  ('manca concessione', 'prontuario', '025-1', 5, true),
  ('mancanza concessione', 'prontuario', '025-1', 5, true),
  ('sosta contromano', 'prontuario', '157-4', 10, true),
  ('parcheggia sulla sinistra', 'prontuario', '157-4', 10, true),
  ('senza avere certificato di circolazione', 'prontuario', '097-14', 5, true),
  ('senza assicurazione e documenti falsi', 'prontuario', '193-4', 10, true),
  ('assicurazione e documenti contraffatti', 'prontuario', '193-4', 10, true),
  ('polizza assicurativa falsa', 'prontuario', '193-4', 10, true),
  ('senza usare le dovute cautele', 'prontuario', '063-5', 5, true),
  ('manca usare le dovute cautele', 'prontuario', '063-5', 5, true),
  ('mancanza usare le dovute cautele', 'prontuario', '063-5', 5, true),
  ('senza specifico attestato', 'prontuario', '126-5', 5, true),
  ('manca specifico attestato', 'prontuario', '126-5', 5, true),
  ('mancanza specifico attestato', 'prontuario', '126-5', 5, true),
  ('senza autorizzazione', 'prontuario', '010-26', 5, true),
  ('manca autorizzazione', 'prontuario', '010-26', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-26', 5, true),
  ('sorpasso vietato', 'prontuario', '148-4', 10, true),
  ('sorpasso non consentito', 'prontuario', '148-4', 10, true),
  ('sorpassa dove non può', 'prontuario', '148-4', 10, true),
  ('senza targa posteriore di riconoscimento', 'prontuario', '114-8', 5, true),
  ('manca targa posteriore di riconoscimento', 'prontuario', '114-8', 5, true),
  ('mancanza targa posteriore di riconoscimento', 'prontuario', '114-8', 5, true),
  ('senza autorizzazione', 'prontuario', '009-1', 5, true),
  ('manca autorizzazione', 'prontuario', '009-1', 5, true),
  ('mancanza autorizzazione', 'prontuario', '009-1', 5, true),
  ('senza autorizzazione', 'prontuario', '010-2', 5, true),
  ('manca autorizzazione', 'prontuario', '010-2', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-2', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-20', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-20', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-20', 5, true),
  ('senza pneumatici e/o catene da neve', 'prontuario', '006-11', 5, true),
  ('manca pneumatici e/o catene da neve', 'prontuario', '006-11', 5, true),
  ('mancanza pneumatici e/o catene da neve', 'prontuario', '006-11', 5, true),
  ('passeggero senza casco portato dal conducente', 'prontuario', '171-2', 10, true),
  ('trasporta passeggero senza casco', 'prontuario', '171-2', 10, true),
  ('eccesso di velocità recidiva', 'prontuario', '142-3bis', 10, true),
  ('seconda volta velocità troppo alta', 'prontuario', '142-3bis', 10, true),
  ('senza targa ripetitrice', 'prontuario', '113-2', 5, true),
  ('manca targa ripetitrice', 'prontuario', '113-2', 5, true),
  ('mancanza targa ripetitrice', 'prontuario', '113-2', 5, true),
  ('senza autorizzazione con veicolo', 'prontuario', '010-36', 5, true),
  ('manca autorizzazione con veicolo', 'prontuario', '010-36', 5, true),
  ('mancanza autorizzazione con veicolo', 'prontuario', '010-36', 5, true),
  ('senza attenersi alle prescrizioni sulla circolazione', 'prontuario', '182-7', 5, true),
  ('manca attenersi alle prescrizioni sulla circolazione', 'prontuario', '182-7', 5, true),
  ('mancanza attenersi alle prescrizioni sulla circolazione', 'prontuario', '182-7', 5, true),
  ('senza patente', 'prontuario', '116-2', 10, true),
  ('guida senza patente', 'prontuario', '116-2', 10, true),
  ('manca patente', 'prontuario', '116-2', 10, true),
  ('mancanza patente', 'prontuario', '116-2', 10, true),
  ('mai preso la patente', 'prontuario', '116-2', 10, true),
  ('senza aver mai preso la patente', 'prontuario', '116-2', 10, true),
  ('patente mai conseguita', 'prontuario', '116-2', 10, true),
  ('senza essere munito della prescritta patente', 'prontuario', '124-2', 5, true),
  ('senza osservarne le norme', 'prontuario', '010-6', 5, true),
  ('manca osservarne le norme', 'prontuario', '010-6', 5, true),
  ('mancanza osservarne le norme', 'prontuario', '010-6', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-22', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-22', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-22', 5, true),
  ('senza documento', 'prontuario', '093.bis-3', 5, true),
  ('manca documento', 'prontuario', '093.bis-3', 5, true),
  ('mancanza documento', 'prontuario', '093.bis-3', 5, true),
  ('fuga dopo incidente con feriti', 'prontuario', '189-3', 10, true),
  ('pirata della strada', 'prontuario', '189-3', 10, true),
  ('si allontana dopo incidente con persone ferite', 'prontuario', '189-3', 10, true),
  ('omissione di soccorso', 'prontuario', '189-3', 10, true),
  ('senza licenza', 'prontuario', '086-1', 5, true),
  ('manca licenza', 'prontuario', '086-1', 5, true),
  ('mancanza licenza', 'prontuario', '086-1', 5, true),
  ('patente revocata', 'prontuario', '116-3', 10, true),
  ('guida con patente revocata', 'prontuario', '116-3', 10, true),
  ('patente ritirata guida lo stesso', 'prontuario', '116-3', 10, true),
  ('senza autorizzazione', 'prontuario', '010-46', 5, true),
  ('manca autorizzazione', 'prontuario', '010-46', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-46', 5, true),
  ('passa col rosso recidiva', 'prontuario', '146-5', 10, true),
  ('semaforo rosso di nuovo', 'prontuario', '146-5', 10, true),
  ('senza aver compiuto 24 anni', 'prontuario', '115-8', 5, true),
  ('senza targa', 'prontuario', '067-1', 5, true),
  ('manca targa', 'prontuario', '067-1', 5, true),
  ('mancanza targa', 'prontuario', '067-1', 5, true),
  ('senza strumenti urbanistici', 'prontuario', '018-1', 5, true),
  ('manca strumenti urbanistici', 'prontuario', '018-1', 5, true),
  ('mancanza strumenti urbanistici', 'prontuario', '018-1', 5, true),
  ('guida senza occhiali', 'prontuario', '173-1', 10, true),
  ('senza occhiali prescritti', 'prontuario', '173-1', 10, true),
  ('manca uso occhiali obbligatori', 'prontuario', '173-1', 10, true),
  ('senza conducente', 'prontuario', '084-3', 5, true),
  ('manca conducente', 'prontuario', '084-3', 5, true),
  ('mancanza conducente', 'prontuario', '084-3', 5, true),
  ('senza aver compiuto 18 anni', 'prontuario', '115-5', 5, true),
  ('senza avere con sé l''autorizzazione', 'prontuario', '104-3', 5, true),
  ('senza autorizzazione con veicolo', 'prontuario', '010-57', 5, true),
  ('manca autorizzazione con veicolo', 'prontuario', '010-57', 5, true),
  ('mancanza autorizzazione con veicolo', 'prontuario', '010-57', 5, true),
  ('non presta soccorso', 'prontuario', '189-4', 10, true),
  ('non aiuta il ferito', 'prontuario', '189-4', 10, true),
  ('omette soccorso al ferito', 'prontuario', '189-4', 10, true),
  ('senza licenza', 'prontuario', '086-2', 5, true),
  ('manca licenza', 'prontuario', '086-2', 5, true),
  ('mancanza licenza', 'prontuario', '086-2', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-55', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-55', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-55', 5, true),
  ('officina non rispetta termini revisione', 'prontuario', '080-6', 10, true),
  ('centro revisioni in ritardo', 'prontuario', '080-6', 10, true),
  ('senza la certificazione rilasciata dall’autoscuola', 'prontuario', '122-07', 5, true),
  ('manca la certificazione rilasciata dall’autoscuola', 'prontuario', '122-07', 5, true),
  ('mancanza la certificazione rilasciata dall’autoscuola', 'prontuario', '122-07', 5, true),
  ('senza far uso delle segnalazioni luminose', 'prontuario', '184-3', 5, true),
  ('manca far uso delle segnalazioni luminose', 'prontuario', '184-3', 5, true),
  ('mancanza far uso delle segnalazioni luminose', 'prontuario', '184-3', 5, true),
  ('senza targa', 'prontuario', '097-6', 5, true),
  ('manca targa', 'prontuario', '097-6', 5, true),
  ('mancanza targa', 'prontuario', '097-6', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-43', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-43', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-43', 5, true),
  ('guida ubriaco tasso medio', 'prontuario', '186-2', 10, true),
  ('ebbrezza tasso medio', 'prontuario', '186-2', 10, true),
  ('alcol test tasso medio', 'prontuario', '186-2', 10, true),
  ('senza casco', 'prontuario', '171-1', 10, true),
  ('guida senza casco', 'prontuario', '171-1', 10, true),
  ('manca casco', 'prontuario', '171-1', 10, true),
  ('mancanza casco', 'prontuario', '171-1', 10, true),
  ('casco non indossato', 'prontuario', '171-1', 10, true),
  ('non rispetta agente di traffico', 'prontuario', '146-6', 10, true),
  ('ignora il vigile che dirige il traffico', 'prontuario', '146-6', 10, true),
  ('senza avere compiuto 14 anni', 'prontuario', '115-2', 5, true),
  ('senza usare le dovute cautele', 'prontuario', '063-4', 5, true),
  ('manca usare le dovute cautele', 'prontuario', '063-4', 5, true),
  ('mancanza usare le dovute cautele', 'prontuario', '063-4', 5, true),
  ('senza autorizzazione', 'prontuario', '082-4', 5, true),
  ('manca autorizzazione', 'prontuario', '082-4', 5, true),
  ('mancanza autorizzazione', 'prontuario', '082-4', 5, true),
  ('senza targa posteriore di riconoscimento', 'prontuario', '113-1', 5, true),
  ('manca targa posteriore di riconoscimento', 'prontuario', '113-1', 5, true),
  ('mancanza targa posteriore di riconoscimento', 'prontuario', '113-1', 5, true),
  ('eccesso di velocità fino a 10', 'prontuario', '142-1', 10, true),
  ('supera limite di poco', 'prontuario', '142-1', 10, true),
  ('velocità leggermente superiore', 'prontuario', '142-1', 10, true),
  ('senza prescrizioni per conto terzi', 'prontuario', '023-9', 5, true),
  ('manca prescrizioni per conto terzi', 'prontuario', '023-9', 5, true),
  ('mancanza prescrizioni per conto terzi', 'prontuario', '023-9', 5, true),
  ('senza dispositivo di frenatura', 'prontuario', '105-3', 5, true),
  ('manca dispositivo di frenatura', 'prontuario', '105-3', 5, true),
  ('mancanza dispositivo di frenatura', 'prontuario', '105-3', 5, true),
  ('senza sistemi di ritenuta', 'prontuario', '172-5', 5, true),
  ('manca sistemi di ritenuta', 'prontuario', '172-5', 5, true),
  ('mancanza sistemi di ritenuta', 'prontuario', '172-5', 5, true),
  ('bambino senza seggiolino', 'prontuario', '172-2', 10, true),
  ('minore senza seggiolino', 'prontuario', '172-2', 10, true),
  ('senza seggiolino auto', 'prontuario', '172-2', 10, true),
  ('manca seggiolino bambino', 'prontuario', '172-2', 10, true),
  ('senza autorizzazione', 'prontuario', '009-bis-6', 5, true),
  ('manca autorizzazione', 'prontuario', '009-bis-6', 5, true),
  ('mancanza autorizzazione', 'prontuario', '009-bis-6', 5, true),
  ('senza adottare le opportune cautele', 'prontuario', '158-54', 5, true),
  ('assicurazione non operativa', 'prontuario', '193-3', 10, true),
  ('assicurazione non ancora attiva', 'prontuario', '193-3', 10, true),
  ('polizza non operativa', 'prontuario', '193-3', 10, true),
  ('assicurazione sospesa', 'prontuario', '193-5', 10, true),
  ('polizza sospesa', 'prontuario', '193-5', 10, true),
  ('copertura assicurativa sospesa', 'prontuario', '193-5', 10, true),
  ('guida ubriaco tasso alto', 'prontuario', '186-3', 10, true),
  ('ebbrezza tasso alto', 'prontuario', '186-3', 10, true),
  ('molto ubriaco alla guida', 'prontuario', '186-3', 10, true),
  ('porte aperte pericolo', 'prontuario', '157-7', 10, true),
  ('lascia porte aperte in strada', 'prontuario', '157-7', 10, true),
  ('patente non adatta al veicolo', 'prontuario', '116-4', 10, true),
  ('guida veicolo non abilitato dalla patente', 'prontuario', '116-4', 10, true),
  ('categoria patente sbagliata', 'prontuario', '116-4', 10, true),
  ('fermata vietata', 'prontuario', '157-1', 10, true),
  ('si ferma dove non può', 'prontuario', '157-1', 10, true),
  ('fermata irregolare', 'prontuario', '157-1', 10, true),
  ('senza rispettare le prescrizioni previste nell''autorizzazione', 'prontuario', '086-7', 5, true),
  ('patente scaduta', 'prontuario', '126-1', 10, true),
  ('guida con patente scaduta', 'prontuario', '126-1', 10, true),
  ('patente di guida scaduta', 'prontuario', '126-1', 10, true),
  ('cqc scaduta', 'prontuario', '126-1', 10, true),
  ('cap scaduto', 'prontuario', '126-1', 10, true),
  ('rifiuta alcol test', 'prontuario', '186-7', 10, true),
  ('si rifiuta di soffiare nel palloncino', 'prontuario', '186-7', 10, true),
  ('rifiuta etilometro', 'prontuario', '186-7', 10, true),
  ('senza autorizzazione', 'prontuario', '007-25', 5, true),
  ('manca autorizzazione', 'prontuario', '007-25', 5, true),
  ('mancanza autorizzazione', 'prontuario', '007-25', 5, true),
  ('senza seguire le condizioni previste', 'prontuario', '172-6', 5, true),
  ('senza requisiti di cui all''art', 'prontuario', '060-4', 5, true),
  ('manca requisiti di cui all''art', 'prontuario', '060-4', 5, true),
  ('mancanza requisiti di cui all''art', 'prontuario', '060-4', 5, true),
  ('passa col rosso', 'prontuario', '146-4', 10, true),
  ('semaforo rosso', 'prontuario', '146-4', 10, true),
  ('non si ferma al rosso', 'prontuario', '146-4', 10, true),
  ('brucia il semaforo', 'prontuario', '146-4', 10, true),
  ('attraversa col rosso', 'prontuario', '146-4', 10, true),
  ('senza rispettare le distanze', 'prontuario', '020-6', 5, true),
  ('senza autorizzazione', 'prontuario', '010-44', 5, true),
  ('manca autorizzazione', 'prontuario', '010-44', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-44', 5, true),
  ('senza osservare le prescrizioni', 'prontuario', '007-15', 5, true),
  ('senza aver compiuto 16 anni', 'prontuario', '115-4', 5, true),
  ('senza autorizzazione', 'prontuario', '009-bis-1', 5, true),
  ('manca autorizzazione', 'prontuario', '009-bis-1', 5, true),
  ('mancanza autorizzazione', 'prontuario', '009-bis-1', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-12', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-12', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-12', 5, true),
  ('senza autorizzazione', 'prontuario', '010-3', 5, true),
  ('manca autorizzazione', 'prontuario', '010-3', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-3', 5, true),
  ('senza sistema di ritenuta per bambini', 'prontuario', '172-7', 5, true),
  ('manca sistema di ritenuta per bambini', 'prontuario', '172-7', 5, true),
  ('mancanza sistema di ritenuta per bambini', 'prontuario', '172-7', 5, true),
  ('certificato di revisione falso', 'prontuario', '080-8', 10, true),
  ('documento di revisione falsificato', 'prontuario', '080-8', 10, true),
  ('senza la presenza dell''isola salvagente', 'prontuario', '148-10', 5, true),
  ('manca la presenza dell''isola salvagente', 'prontuario', '148-10', 5, true),
  ('mancanza la presenza dell''isola salvagente', 'prontuario', '148-10', 5, true),
  ('veicolo sospeso recidiva', 'prontuario', '080-5', 10, true),
  ('circola ancora con veicolo sospeso', 'prontuario', '080-5', 10, true),
  ('sorpasso in curva', 'prontuario', '148-12', 10, true),
  ('sorpassa in curva o poca visibilità', 'prontuario', '148-12', 10, true),
  ('guida drogato', 'prontuario', '187-1', 10, true),
  ('sotto effetto di droga alla guida', 'prontuario', '187-1', 10, true),
  ('positivo agli stupefacenti', 'prontuario', '187-1', 10, true),
  ('senza rispettare le distanze', 'prontuario', '020-5', 5, true),
  ('sosta vietata', 'prontuario', '157-2', 10, true),
  ('parcheggio vietato', 'prontuario', '157-2', 10, true),
  ('sosta irregolare', 'prontuario', '157-2', 10, true),
  ('parcheggia dove non può', 'prontuario', '157-2', 10, true),
  ('seggiolino non a norma', 'prontuario', '172-4', 10, true),
  ('dispositivo di ritenuta non idoneo', 'prontuario', '172-4', 10, true),
  ('senza targa anteriore e/o posteriore', 'prontuario', '100-2', 5, true),
  ('manca targa anteriore e/o posteriore', 'prontuario', '100-2', 5, true),
  ('mancanza targa anteriore e/o posteriore', 'prontuario', '100-2', 5, true),
  ('senza dispositivo di segnalazione visiva', 'prontuario', '068-1', 5, true),
  ('manca dispositivo di segnalazione visiva', 'prontuario', '068-1', 5, true),
  ('mancanza dispositivo di segnalazione visiva', 'prontuario', '068-1', 5, true),
  ('senza usare le dovute cautele', 'prontuario', '063-3', 5, true),
  ('manca usare le dovute cautele', 'prontuario', '063-3', 5, true),
  ('mancanza usare le dovute cautele', 'prontuario', '063-3', 5, true),
  ('senza autorizzazione', 'prontuario', '010-25', 5, true),
  ('manca autorizzazione', 'prontuario', '010-25', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-25', 5, true),
  ('attestazione di revisione falsa', 'prontuario', '080-7', 10, true),
  ('certificato revisione falso rilasciato da officina', 'prontuario', '080-7', 10, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-64', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-64', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-64', 5, true),
  ('senza autorizzazione', 'prontuario', '010-1', 5, true),
  ('manca autorizzazione', 'prontuario', '010-1', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-1', 5, true),
  ('senza osservarne le norme', 'prontuario', '010-48', 5, true),
  ('manca osservarne le norme', 'prontuario', '010-48', 5, true),
  ('mancanza osservarne le norme', 'prontuario', '010-48', 5, true),
  ('senza targa anteriore e/o posteriore', 'prontuario', '100-1', 5, true),
  ('manca targa anteriore e/o posteriore', 'prontuario', '100-1', 5, true),
  ('mancanza targa anteriore e/o posteriore', 'prontuario', '100-1', 5, true),
  ('senza il contrassegno relativo all''indennizzo d''usura', 'prontuario', '034-1', 5, true),
  ('manca il contrassegno relativo all''indennizzo d''usura', 'prontuario', '034-1', 5, true),
  ('mancanza il contrassegno relativo all''indennizzo d''usura', 'prontuario', '034-1', 5, true),
  ('senza assicurazione', 'prontuario', '193-1', 10, true),
  ('guida senza assicurazione', 'prontuario', '193-1', 10, true),
  ('circola senza assicurazione', 'prontuario', '193-1', 10, true),
  ('manca assicurazione', 'prontuario', '193-1', 10, true),
  ('mancanza assicurazione', 'prontuario', '193-1', 10, true),
  ('senza rca', 'prontuario', '193-1', 10, true),
  ('senza copertura assicurativa', 'prontuario', '193-1', 10, true),
  ('assicurazione mancante', 'prontuario', '193-1', 10, true),
  ('senza autorizzazione con veicolo', 'prontuario', '010-14', 5, true),
  ('manca autorizzazione con veicolo', 'prontuario', '010-14', 5, true),
  ('mancanza autorizzazione con veicolo', 'prontuario', '010-14', 5, true),
  ('senza autorizzazione', 'prontuario', '009-2', 5, true),
  ('manca autorizzazione', 'prontuario', '009-2', 5, true),
  ('mancanza autorizzazione', 'prontuario', '009-2', 5, true),
  ('sorpasso pericoloso', 'prontuario', '148-1', 10, true),
  ('sorpasso non in sicurezza', 'prontuario', '148-1', 10, true),
  ('sorpasso rischioso', 'prontuario', '148-1', 10, true),
  ('senza autorizzazione', 'prontuario', '010-4', 5, true),
  ('manca autorizzazione', 'prontuario', '010-4', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-4', 5, true),
  ('senza osservarne le norme', 'prontuario', '010-5', 5, true),
  ('manca osservarne le norme', 'prontuario', '010-5', 5, true),
  ('mancanza osservarne le norme', 'prontuario', '010-5', 5, true),
  ('senza sigla distintiva dello stato', 'prontuario', '133-1', 5, true),
  ('manca sigla distintiva dello stato', 'prontuario', '133-1', 5, true),
  ('mancanza sigla distintiva dello stato', 'prontuario', '133-1', 5, true),
  ('senza pneumatici e/o catene da neve', 'prontuario', '006-11bis', 5, true),
  ('manca pneumatici e/o catene da neve', 'prontuario', '006-11bis', 5, true),
  ('mancanza pneumatici e/o catene da neve', 'prontuario', '006-11bis', 5, true),
  ('telefono alla guida', 'prontuario', '173-2', 10, true),
  ('cellulare alla guida', 'prontuario', '173-2', 10, true),
  ('usa il telefono guidando', 'prontuario', '173-2', 10, true),
  ('usa lo smartphone guidando', 'prontuario', '173-2', 10, true),
  ('guida col telefono in mano', 'prontuario', '173-2', 10, true),
  ('chatta al telefono guidando', 'prontuario', '173-2', 10, true),
  ('senza strumenti urbanistici', 'prontuario', '016-2', 5, true),
  ('manca strumenti urbanistici', 'prontuario', '016-2', 5, true),
  ('mancanza strumenti urbanistici', 'prontuario', '016-2', 5, true),
  ('proprietario permette circolazione senza assicurazione', 'prontuario', '193-6', 10, true),
  ('presta veicolo senza assicurazione', 'prontuario', '193-6', 10, true),
  ('senza autorizzazione', 'prontuario', '010-24', 5, true),
  ('manca autorizzazione', 'prontuario', '010-24', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-24', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-34', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-34', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-34', 5, true),
  ('senza relativa omologazione', 'prontuario', '068-3', 5, true),
  ('manca relativa omologazione', 'prontuario', '068-3', 5, true),
  ('mancanza relativa omologazione', 'prontuario', '068-3', 5, true),
  ('senza autorizzazione', 'prontuario', '010-45', 5, true),
  ('manca autorizzazione', 'prontuario', '010-45', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-45', 5, true),
  ('senza autorizzazione dell''ente proprietario', 'prontuario', '023-4', 5, true),
  ('manca autorizzazione dell''ente proprietario', 'prontuario', '023-4', 5, true),
  ('mancanza autorizzazione dell''ente proprietario', 'prontuario', '023-4', 5, true),
  ('senza autorizzazione', 'prontuario', '122-1', 5, true),
  ('manca autorizzazione', 'prontuario', '122-1', 5, true),
  ('mancanza autorizzazione', 'prontuario', '122-1', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-41', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-41', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-41', 5, true),
  ('senza revisione recidiva', 'prontuario', '080-3', 10, true),
  ('revisione scaduta recidiva', 'prontuario', '080-3', 10, true),
  ('senza revisione di nuovo', 'prontuario', '080-3', 10, true),
  ('senza requisiti di cui all''art', 'prontuario', '060-3', 5, true),
  ('manca requisiti di cui all''art', 'prontuario', '060-3', 5, true),
  ('mancanza requisiti di cui all''art', 'prontuario', '060-3', 5, true),
  ('telefono alla guida recidiva', 'prontuario', '173-3', 10, true),
  ('cellulare alla guida di nuovo', 'prontuario', '173-3', 10, true),
  ('guida ubriaco', 'prontuario', '186-1', 10, true),
  ('alla guida in stato di ebbrezza', 'prontuario', '186-1', 10, true),
  ('positivo all''alcol test', 'prontuario', '186-1', 10, true),
  ('tasso alcolemico basso', 'prontuario', '186-1', 10, true),
  ('guida dopo aver bevuto poco', 'prontuario', '186-1', 10, true),
  ('senza patente o certificato d''idoneità', 'prontuario', '118-1', 5, true),
  ('manca patente o certificato d''idoneità', 'prontuario', '118-1', 5, true),
  ('mancanza patente o certificato d''idoneità', 'prontuario', '118-1', 5, true),
  ('senza il rilascio dell''autorizzazione', 'prontuario', '024-1', 5, true),
  ('manca il rilascio dell''autorizzazione', 'prontuario', '024-1', 5, true),
  ('mancanza il rilascio dell''autorizzazione', 'prontuario', '024-1', 5, true),
  ('senza dispositivo antiabbandono', 'prontuario', '172-3', 10, true),
  ('manca allarme antiabbandono', 'prontuario', '172-3', 10, true),
  ('senza allarme bambino a bordo', 'prontuario', '172-3', 10, true),
  ('senza autorizzazione', 'prontuario', '122-3', 5, true),
  ('manca autorizzazione', 'prontuario', '122-3', 5, true),
  ('mancanza autorizzazione', 'prontuario', '122-3', 5, true),
  ('senza il contrassegno relativo all''indennizzo d''usura', 'prontuario', '034-2', 5, true),
  ('manca il contrassegno relativo all''indennizzo d''usura', 'prontuario', '034-2', 5, true),
  ('mancanza il contrassegno relativo all''indennizzo d''usura', 'prontuario', '034-2', 5, true),
  ('fuga dopo incidente solo danni', 'prontuario', '189-1', 10, true),
  ('si allontana dopo incidente senza feriti', 'prontuario', '189-1', 10, true),
  ('pirata della strada senza feriti', 'prontuario', '189-1', 10, true),
  ('senza osservare le prescrizioni', 'prontuario', '006-03', 5, true),
  ('veicolo sospeso circola comunque', 'prontuario', '080-4', 10, true),
  ('circola con veicolo sospeso dalla circolazione', 'prontuario', '080-4', 10, true),
  ('senza regolare concessione', 'prontuario', '015-11', 5, true),
  ('sorpasso a destra', 'prontuario', '148-2', 10, true),
  ('supera sulla destra', 'prontuario', '148-2', 10, true),
  ('senza conducente', 'prontuario', '084-5', 5, true),
  ('manca conducente', 'prontuario', '084-5', 5, true),
  ('mancanza conducente', 'prontuario', '084-5', 5, true),
  ('senza certificato d''idoneità', 'prontuario', '118-3', 5, true),
  ('manca certificato d''idoneità', 'prontuario', '118-3', 5, true),
  ('mancanza certificato d''idoneità', 'prontuario', '118-3', 5, true),
  ('senza targa', 'prontuario', '097-7', 5, true),
  ('manca targa', 'prontuario', '097-7', 5, true),
  ('mancanza targa', 'prontuario', '097-7', 5, true),
  ('senza cintura', 'prontuario', '172-1', 10, true),
  ('senza cinture di sicurezza', 'prontuario', '172-1', 10, true),
  ('manca cintura', 'prontuario', '172-1', 10, true),
  ('cintura non allacciata', 'prontuario', '172-1', 10, true),
  ('non indossa la cintura', 'prontuario', '172-1', 10, true),
  ('senza essere munito della prescritta patente', 'prontuario', '124-1', 5, true),
  ('sorpasso di veicoli fermi in fila', 'prontuario', '148-14', 10, true),
  ('supera veicoli in coda fermi', 'prontuario', '148-14', 10, true),
  ('senza adottare le opportune cautele', 'prontuario', '158-55', 5, true),
  ('senza specifico attestato', 'prontuario', '126-4', 5, true),
  ('manca specifico attestato', 'prontuario', '126-4', 5, true),
  ('mancanza specifico attestato', 'prontuario', '126-4', 5, true),
  ('senza revisione', 'prontuario', '080-1', 10, true),
  ('manca revisione', 'prontuario', '080-1', 10, true),
  ('mancanza revisione', 'prontuario', '080-1', 10, true),
  ('revisione scaduta', 'prontuario', '080-1', 10, true),
  ('revisione non fatta', 'prontuario', '080-1', 10, true),
  ('senza bollino revisione', 'prontuario', '080-1', 10, true),
  ('senza bollino blu', 'prontuario', '080-1', 10, true),
  ('senza autorizzazione', 'prontuario', '010-23', 5, true),
  ('manca autorizzazione', 'prontuario', '010-23', 5, true),
  ('mancanza autorizzazione', 'prontuario', '010-23', 5, true),
  ('senza autorizzazione', 'prontuario', '007-24', 5, true),
  ('manca autorizzazione', 'prontuario', '007-24', 5, true),
  ('mancanza autorizzazione', 'prontuario', '007-24', 5, true),
  ('rifiuta test antidroga', 'prontuario', '187-3', 10, true),
  ('si rifiuta accertamento droga', 'prontuario', '187-3', 10, true),
  ('senza targa anteriore e/o posteriore', 'prontuario', '100-3', 5, true),
  ('manca targa anteriore e/o posteriore', 'prontuario', '100-3', 5, true),
  ('mancanza targa anteriore e/o posteriore', 'prontuario', '100-3', 5, true),
  ('senza osservarne le norme', 'prontuario', '010-28', 5, true),
  ('manca osservarne le norme', 'prontuario', '010-28', 5, true),
  ('mancanza osservarne le norme', 'prontuario', '010-28', 5, true),
  ('senza limiti di scadenza amministrativa', 'prontuario', '136.bis-1', 5, true),
  ('manca limiti di scadenza amministrativa', 'prontuario', '136.bis-1', 5, true),
  ('mancanza limiti di scadenza amministrativa', 'prontuario', '136.bis-1', 5, true),
  ('senza tenere accese le luci prescritte', 'prontuario', '176-13', 5, true),
  ('senza speciale targa', 'prontuario', '113-3', 5, true),
  ('manca speciale targa', 'prontuario', '113-3', 5, true),
  ('mancanza speciale targa', 'prontuario', '113-3', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-63', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-63', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-63', 5, true),
  ('senza licenza', 'prontuario', '070-2', 5, true),
  ('manca licenza', 'prontuario', '070-2', 5, true),
  ('mancanza licenza', 'prontuario', '070-2', 5, true),
  ('senza aver compiuto 21 anni', 'prontuario', '115-6', 5, true),
  ('senza osservarne le norme', 'prontuario', '010-27', 5, true),
  ('manca osservarne le norme', 'prontuario', '010-27', 5, true),
  ('mancanza osservarne le norme', 'prontuario', '010-27', 5, true),
  ('senza conducente', 'prontuario', '084-4', 5, true),
  ('manca conducente', 'prontuario', '084-4', 5, true),
  ('mancanza conducente', 'prontuario', '084-4', 5, true),
  ('passeggero senza casco', 'prontuario', '171-3', 10, true),
  ('passeggero senza casco protettivo', 'prontuario', '171-3', 10, true),
  ('senza sistema di ritenuta per bambini', 'prontuario', '172-8', 5, true),
  ('manca sistema di ritenuta per bambini', 'prontuario', '172-8', 5, true),
  ('mancanza sistema di ritenuta per bambini', 'prontuario', '172-8', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-21', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-21', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-21', 5, true),
  ('senza autorizzazione', 'prontuario', '009-bis-2', 5, true),
  ('manca autorizzazione', 'prontuario', '009-bis-2', 5, true),
  ('mancanza autorizzazione', 'prontuario', '009-bis-2', 5, true),
  ('senza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-42', 5, true),
  ('manca autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-42', 5, true),
  ('mancanza autorizzazione con veicolo mezzo d''opera', 'prontuario', '010-42', 5, true),
  ('senza revisione straordinaria', 'prontuario', '080-2', 10, true),
  ('manca revisione straordinaria', 'prontuario', '080-2', 10, true),
  ('senza mantenere la posizione', 'prontuario', '143-6', 5, true),
  ('senza richiedere l''aggiornamento', 'prontuario', '097-12', 5, true),
  ('senza adottare le dovute cautele', 'prontuario', '104-2', 5, true),
  ('senza rispettare le prescrizioni contenute nell''autorizzazione', 'prontuario', '020-3', 5, true);
